const fragrances=[['01','AMBER OUD','SAFFRON · AMBER · OUD · CEDAR · RESIN · MUSK','amber-oud.html'],['02','SANTAL NOIR','CARDAMOM · SANDALWOOD · DRY WOODS · AMBER','collection.html'],['03','CONCRETE RAIN','BERGAMOT · JUNIPER · MINERAL · CEDAR','collection.html'],['04','STATIC WOOD','MANDARIN · PINK PEPPER · VETIVER · AMBER','collection.html'],['00','NULL','FRAGRANCE-FREE SOLID','collection.html']];
const products=[{name:'AMBER OUD',type:'EAU DE DÉODORANT · 100 ML',price:39,kind:'spray',link:'amber-oud.html'},{name:'OBJECT 01',type:'REFILLABLE SOLID · STARTER',price:29,kind:'stick',link:'object-01.html'},{name:'THE RITUAL',type:'OBJECT 01 + AMBER OUD',price:59,kind:'both',link:'the-ritual.html'}];
const productGrid=document.querySelector('#products');if(productGrid)productGrid.innerHTML=products.map((p,i)=>`<article class="product"><a href="${p.link}" class="product-visual" aria-label="Discover ${p.name}">${visual(p.kind)}</a><p>0${i+1} / OFFSETT</p><h3><a href="${p.link}">${p.name}</a></h3><p>${p.type}</p><div class="product-foot"><b>€${p.price}</b><button class="add" data-i="${i}">ADD TO BAG +</button></div></article>`).join('');
function visual(kind){let s='<div class="spray mini-spray"><span>OFFSETT</span><b>01</b><small>AMBER OUD<br>EAU DE DÉODORANT</small></div>',t='<div class="stick mini-stick"><span>OFFSETT</span><i></i><small>OBJECT 01</small></div>';return kind==='spray'?s:kind==='stick'?t:`<div style="display:flex;gap:5px">${s}${t}</div>`}
const fragranceGrid=document.querySelector('#fragranceGrid');if(fragranceGrid)fragranceGrid.innerHTML=fragrances.map(x=>`<a class="fragrance-row" href="${x[3]}"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p><span>↗</span></a>`).join('');
const CART='offsett-bag-v1';let cart=[];try{cart=JSON.parse(localStorage.getItem(CART)||'[]').filter(i=>products[i.id]&&Number.isInteger(i.quantity)&&i.quantity>0)}catch{cart=[]}
const drawer=document.querySelector('#drawer'),veil=document.querySelector('#veil');function persist(){localStorage.setItem(CART,JSON.stringify(cart))}function total(){return cart.reduce((sum,item)=>sum+products[item.id].price*item.quantity,0)}function render(){const count=document.querySelector('#count');if(count)count.textContent=cart.reduce((n,i)=>n+i.quantity,0);const items=document.querySelector('#cartItems');if(items)items.innerHTML=cart.length?cart.map((item)=>`<div class="cartitem"><span>${products[item.id].name} × ${item.quantity}<br><small>${products[item.id].type}</small></span><span>€${products[item.id].price*item.quantity} <button data-remove="${item.id}" aria-label="Remove ${products[item.id].name}">×</button></span></div>`).join(''):'<p>Your bag is empty.</p>';const sub=document.querySelector('#subtotal');if(sub)sub.textContent='€'+total();const checkoutItems=document.querySelector('#checkoutItems');if(checkoutItems)checkoutItems.innerHTML=cart.length?cart.map(item=>`<div class="checkout-line"><span><strong>${products[item.id].name} × ${item.quantity}</strong><small>${products[item.id].type}</small><br><button data-remove="${item.id}">REMOVE</button></span><b>€${products[item.id].price*item.quantity}</b></div>`).join(''):'<p>Your bag is empty. <a href="collection.html">Explore the collection ↗</a></p>';const checkoutSub=document.querySelector('#checkoutSubtotal');if(checkoutSub)checkoutSub.textContent='€'+total();document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>remove(Number(b.dataset.remove)));document.querySelectorAll('.add').forEach(b=>b.onclick=()=>add(Number(b.dataset.i)));document.querySelectorAll('[data-reveal]').forEach(el=>observer&&observer.observe(el));}
function add(id){const found=cart.find(i=>i.id===id);if(found)found.quantity+=1;else cart.push({id,quantity:1});persist();render();openCart()}function remove(id){cart=cart.filter(i=>i.id!==id);persist();render()}function openCart(){drawer?.classList.add('open');veil?.classList.add('on')}function closeCart(){drawer?.classList.remove('open');veil?.classList.remove('on')}
document.querySelector('#cartBtn')?.addEventListener('click',openCart);document.querySelector('#closeCart')?.addEventListener('click',closeCart);veil?.addEventListener('click',closeCart);render();
const observer='IntersectionObserver'in window?new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12}):null;
document.querySelectorAll('main section:not(.hero),.product,.fragrance-row').forEach((el,i)=>{el.dataset.reveal='';el.style.transitionDelay=(i%4)*65+'ms';if(observer)observer.observe(el);else el.classList.add('is-visible')});
const payBtn=document.querySelector('#payBtn');payBtn?.addEventListener('click',async()=>{const note=document.querySelector('#checkoutNote');if(!cart.length){note.textContent='Your bag is empty. Choose something from the collection first.';return}payBtn.disabled=true;note.textContent='Connecting to secure checkout…';try{const response=await fetch(new URL('api/checkout',location.href),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:cart})});if(response.status===404)throw new Error('Secure checkout is not connected on GitHub Pages. Host this repository on Cloudflare Pages and add STRIPE_SECRET_KEY to activate payments.');let result;try{result=await response.json()}catch{throw new Error('Secure checkout returned an invalid response. Check that the Cloudflare Pages function is deployed.')}if(!response.ok)throw new Error(result.error||'Checkout could not be started.');if(!result.url)throw new Error('The checkout provider returned no secure checkout URL.');location.href=result.url}catch(error){note.textContent=error.message.includes('Failed to fetch')?'Secure checkout is not connected on GitHub Pages. Host this repository on Cloudflare Pages and add STRIPE_SECRET_KEY to activate payments.':error.message;payBtn.disabled=false}});
if(location.pathname.endsWith('/success.html')){localStorage.removeItem(CART);cart=[];render()}
